import type { Metadata } from "next";
import { ReactNode } from "react";
import Providers from "./providers";
import "@/styles/globals.css";
import "@/styles/layout.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <nav>
          <a href="/">Dashboard</a>
          <a href="/employees">Employees</a>
          <a href="/attendance">Attendance</a>
        </nav>
        <main>
          <Providers>{children}</Providers>
        </main>
      </body>
    </html>
  );
}

